### ISSUE TITLE
How to define environment for compiled files

### ISSUE THREAD

**Issue by Evgenus** [xixixao/meta-coffee#4]
I'm trying to use this in node. There is a lot of external stuff in generated files which as obviously undefined.

```
module, __filename, __dirname) { MultiplicativeInterpreter = subclass(OMeta, {
                                                                      ^
ReferenceError: OMeta is not defined
    at Object.<anonymous> (o:\glob-rules\grammar.js:1:100)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by KamilSzot** [comment]
Could you add this line to the examples in Readme.md? 
It could help people trying out your lib.

**Comment by xixixao** [comment]
@KamilSzot Done. I welcome anyone to take a stab at better fixing this.
